# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Build the app"
  lane :build do
    match(app_identifier: ["io.oneiro.buoyantwallet"], type: "appstore", readonly: true)
    build_app(
      scheme: "buoyantwallet",
      include_symbols: false,
      export_method: "app-store",
      export_options: {
          provisioningProfiles: {
              "io.oneiro.buoyantwallet" => "match AppStore io.oneiro.buoyantwallet"
          }
      }
    )
  end
end
